(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var w2=function(a){a.S("cardstatechange",g.rL(a)&&g.sL(a)?1:0)},nta=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ek&&a.dataset){if(g.Sc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.nd("pollChoiceIndex"))},ota=function(a){return Math.pow(a,3)},pta=function(a){return 3*a*a-2*a*a*a},x2=function(a,b){var c=g.Co("use_default_events_client")?void 0:g.Jq;
(0,g.y)(b,function(d){d={csn:a,ve:g.Qr(d),eventType:4};var e={Hj:g.Xr(a),oj:a};"UNDEFINED_CSN"==a?g.js("visualElementShown",d,e):c?g.Zp("visualElementShown",d,c,e):g.Kq("visualElementShown",d,e)})},y2=function(a,b){var c=g.Co("use_default_events_client")?void 0:g.Jq;
(0,g.y)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.Qr(d),eventType:e?16:8};e={Hj:g.Xr(a),oj:a,TE:e};"UNDEFINED_CSN"==a?g.js("visualElementHidden",d,e):c?g.Zp("visualElementHidden",d,c,e):g.Kq("visualElementHidden",d,e)})},B2=function(a){a=g.Pa(a);
delete z2[a];g.Ob(z2)&&A2&&A2.stop()},rta=function(){A2||(A2=new g.H(function(){qta()},20));
var a=A2;a.isActive()||a.start()},qta=function(){var a=(0,g.C)();
g.Bb(z2,function(b){sta(b,a)});
g.Ob(z2)||rta()},C2=function(a,b,c,d){g.Kn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.H=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.G=0;this.C=null},sta=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;tta(a,a.progress);1==a.progress?(a.o=0,B2(a),a.qd(),a.Fm()):a.fb()&&a.qu()},tta=function(a,b){g.Ma(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.H[c]-a.A[c])*b+a.A[c]},uta=function(a,b){g.Ne.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},D2=function(a,b,c,d,e){C2.call(this,b,c,d,e);
this.element=a},E2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
D2.call(this,a,b,c,d,e)},F2=function(a){g.z.call(this);
this.u=a||window;this.o=[]},vta=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.rp(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},G2=function(a){return a.baseUrl||null},H2=function(a,b){return(0,g.ze)((0,g.Hc)(a,b,void 0),function(c){return!!c})},wta=function(a,b,c){function d(cb){var Ya=cb.hovercardButton;
if(!Ya)return null;Ya=Ya.subscribeButtonRenderer;if(!Ya)return null;var de=f(Ya.unsubscribedButtonText),sf=f(Ya.subscribedButtonText);if(Ya.subscribed){var Th=f(Ya.subscriberCountWithUnsubscribeText);var Uh=f(Ya.subscriberCountText)}else Th=f(Ya.subscriberCountText),Uh=f(Ya.subscriberCountWithSubscribeText);var hg=null;return cb.signinEndpoint&&(hg=g.Jb(cb,"signinEndpoint","webNavigationEndpointData","url"),!hg)?null:de&&(sf||hg)?{subscribed:Ya.subscribed,subscribeText:de,subscribeCount:Th,unsubscribeText:sf,
unsubscribeCount:Uh,enabled:Ya.enabled,signinUrl:hg,classic:cb.useClassicSubscribeButton}:null}
function e(cb){if(cb){var Ya=[],de=cb.videoId;de&&Ya.push("v="+de);(de=cb.playlistId)&&Ya.push("list="+de);(cb=cb.startTimeSeconds)&&Ya.push("t="+cb);return"/watch?"+Ya.join("&")}}
function f(cb){if(!cb)return null;var Ya=cb.simpleText;return Ya?Ya:cb.runs?(0,g.Hc)(cb.runs,function(de){return de.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,w=null,B=!1,D=null,E=null,F=null,G=null,aa=null;if("VIDEO"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==h){if(B=g.Jb(l,"browseEndpoint","browseId"))w=B,m="/channel/"+w;n=!1;q="new";(B=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
h?((F=g.Jb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(aa=f(b.additionalFeesText)),(n=g.Jb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Jb(b,"title","accessibility","accessibilityData","label");var ma=b.endpoint?b.endpoint.clickTrackingParams:null,dc="";if(b.metadata){var tb=f(b.metadata);tb&&(dc=tb)}return{id:"element-"+c,type:h,title:f(b.title),metadata:dc,callToAction:f(b.callToAction),
rx:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:w,subscribeButton:D,subscribersText:E,isSubscribe:B,targetUrl:m,qG:n,Tb:{itct:ma},DO:q,ul:a?a:null,uG:b.isPlaceholder,impressionUrls:H2(b.impressionUrls||[],G2),iG:H2(b.hovercardShowUrls||[],G2),clickUrls:H2(l.loggingUrls||[],G2),visualElement:g.Pr(b.trackingParams),productPrice:G,
additionalFeesText:aa}},I2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=H2(a.impressionUrls||[],G2);a.trackingParams&&(c.visualElement=g.Pr(a.trackingParams));c.elements=H2(a.elements||[],function(d,e){return wta(b,d,e)});
return c},J2=function(a){g.OL.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.D=this.A=null;this.J=[];a=a.O();this.R=g.Ny(a)||g.Py(a);this.N=!0;this.H=0;this.C=new g.zr(this);g.A(this,this.C);this.C.M(this.player,g.jC("creatorendscreen"),this.gH);this.C.M(this.player,"crx_creatorendscreen",this.hH);this.C.M(this.player,"resize",this.vz);this.C.M(window,"focus",this.yN);this.load();var b=g.te("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ke(this,function(){g.ye(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},xta=function(a){return a.player.getVideoData().Qb?"current":a.R?"new":"current"},K2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},L2=function(a,b,c){c=void 0===c?!0:c;
g.BR(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.D.dispose(),a.D=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.H=0;if((a.u=b)&&b.elements){c&&yta(a);c=[];d=new g.gC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.Q({F:"div",I:"ytp-ce-shadow"}),g.CL(a.player,a.A.element,4),a.D=new g.yN(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=zta(a,e);a.o[e.id]=f;a.G[e.id]=e;g.CL(a.player,f.element,4);var h=new g.gC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Ata(a,f,e)}g.yL(a.player,c);
a.vz()}},yta=function(a){var b=g.Ur(),c=g.Wr();
c&&b&&a.u.visualElement&&g.ps(c,b,a.u.visualElement)},zta=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={F:"div",Y:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.ul||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",P:M2(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",P:{href:N2(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",Y:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Qn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-video-duration",X:b.videoDuration}]}]};
c=new g.Q(c);break;case "PLAYLIST":c={F:"div",Y:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.ul||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",P:M2(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",P:{href:N2(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",Y:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Qn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-playlist-count",L:[{F:"div",
I:"ytp-ce-playlist-icon"},{F:"div",I:"ytp-ce-playlist-count-text",X:b.playlistLength}]}]}]};c=new g.Q(c);break;case "CHANNEL":c={F:"div",Y:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.ul||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"a",Y:["ytp-ce-channel-title","ytp-ce-link"],P:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Qn(b.title||"")},X:b.title},b.subscribeButton?{F:"div",I:"ytp-ce-subscribe-container",L:[{F:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",I:"ytp-ce-channel-subscribers-text",X:b.subscribersText}:"",b.metadata?{F:"div",Y:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
X:b.metadata}:""]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:M2(b)}]};c=new g.Q(c);var d=g.fe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Tb.itct}else e="endscreen",f=null;e=new g.fR(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":c={F:"div",Y:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.ul||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",I:"ytp-ce-expanding-overlay-body",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-website-title",P:{dir:g.Qn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-website-metadata",X:b.metadata},{F:"a",Y:["ytp-ce-website-goto","ytp-ce-link"],P:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:M2(b)},{F:"div",I:"ytp-ce-expanding-icon",P:Bta(b.iconUrl)}]};c=new g.Q(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={F:"div",I:"ytp-ce-merchandise-price-container",
L:[{F:"div",I:"ytp-ce-merchandise-price",X:b.productPrice}]},b.additionalFeesText&&c.L.push({F:"div",I:"ytp-ce-merchandise-additional-fees",X:b.additionalFeesText})),c={F:"div",Y:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.ul||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",
I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-merchandise-title",P:{dir:g.Qn(b.title||"")},X:b.title},c,{F:"div",I:"ytp-ce-merchandise-metadata",X:b.metadata},{F:"a",Y:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:N2(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:M2(b)},{F:"div",I:"ytp-ce-merchandise-invideo-cta-container",L:[{F:"div",I:"ytp-ce-merchandise-invideo-cta",
X:b.callToAction}]}]},c=new g.Q(c)}b.uG&&g.I(c.element,"ytp-ce-placeholder");return c},M2=function(a){if(a.rx)var b=a.rx.thumbnails;
return Bta(b?b[b.length-1].url:null)},Bta=function(a){return a?{style:"background-image: url("+a+")"}:{}},Ata=function(a,b,c){function d(){h(1)}
function e(){h(-1)}
b.na("mouseenter",(0,g.x)(a.Ht,a,b,c));b.na("mouseleave",(0,g.x)(a.vu,a,b,c));a.player.O().o||b.na("click",(0,g.x)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.na("click",(0,g.x)(a.QA,a,c));b.na("keypress",(0,g.x)(a.QA,a,c));b.na("focus",(0,g.x)(function(l,m){this.Ht(l,m)},a,b,c));
b.na("blur",(0,g.x)(function(l,m){this.vu(l,m)},a,b,c));
b.na("touchstart",(0,g.x)(a.Ht,a,b,c));var f=g.he("ytp-ce-expanding-overlay-hider",b.element);f&&b.M(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.In(b.element,"ytp-ce-element-hover");g.In(b.element,"ytp-ce-force-expand")});
b.na("keydown",(0,g.x)(function(l,m){this.N=9==m.keyCode&&!m.shiftKey},a,b));
var h=(0,g.x)(function(l,m,n){this.H+=n;0<this.H?(g.I(l.element,"ytp-ce-force-expand"),O2(this,m.id,!0)):(g.In(l.element,"ytp-ce-force-expand"),g.In(l.element,"ytp-ce-element-hover"),O2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.na("blur",g.Qa(function(){"none"!=m.style.display&&a.N&&m.focus()})),l.M(m,"focus",d),l.M(m,"blur",e))},a,b);
c(g.he("ytp-sb-subscribe",b.element));c(g.he("ytp-sb-unsubscribe",b.element));b.na("focus",d);b.na("blur",e)},N2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.qz(c)+b}else return"";return b},O2=function(a,b,c){a.A&&(c?a.D.show():a.D.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},P2=function(a,b,c){function d(){f||(e++,e==b.length&&(h.stop(),c&&c()))}
if(!b||0==b.length||K2(a))c&&c();else{b=Cta(a,b);var e=0,f=!1,h=new g.H(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Wq(b[a],d)}},Q2=function(a,b,c){P2(a,b.clickUrls,c);
(a=g.Wr())&&b.qG&&g.qs(a,b.visualElement)},Cta=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Dta(b[e],c));return d},Dta=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Eta=function(a){return Array.isArray(a)&&a.length?a[0]:a},R2=function(a){return"string"===typeof a?a:""},S2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Gta=function(a){var b=Fta;
if(null==a)return null;if(g.La(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Hta=function(a){this.externalId=a},Ita=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},T2=function(a){if(!a)return null;
var b=g.Bc(R2(a.value));b=g.zc(b);if(!b)return null;var c=S2(a.target,Jta,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Ita(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},U2=function(a){return a.value?a.value:null},Kta=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Fta=function(a){if(!a)return null;
var b=S2(a.type,Lta),c=S2(a.trigger,Mta),d=Eta(a.url);d=T2(d?d:null);a=Eta(a.subscribeData);var e=a?a:null;e?(a=R2(e.external_user_id),e=R2(e.subscription_token),a=a&&e?new Hta(a):null):a=null;return b?new Kta(b,c,d,a):null},V2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Nta=function(a,b){return g.Za(a.o,b,void 0)},Ota=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Pta=function(a,b){this.merchant=a;
this.price=b},Qta=function(a){this.o=a},Rta=function(a,b,c){b&&(c?W2(a,(0,g.Hc)(b,g.Qa(function(d,e){return g.jn(e,d)},c))):W2(a,b))},W2=function(a,b,c,d){var e=1,f=-1;
if(c){var h=!1;var l=function(){e--;e||h||(clearTimeout(f),h=!0,c())};
f=setTimeout(function(){h=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Wq(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Sta=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.K=f;this.u=h},X2=function(a,b){this.o=a;
this.A=b},Vta=function(a,b){var c=[];
(0,g.y)(b.choices,function(h){c.push(Tta(b,h))},a);
var d={F:"ul",P:{role:"radiogroup"},L:c},e={};b.rj&&(e["aria-label"]=g.zM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{F:"div",I:"iv-card-content",L:[Y2("h2",e,b.title),{F:"form",L:[{F:"fieldset",L:[d]}]}]}];b.rj&&(f.push("iv-card-unavailable"),d.push({F:"div",Y:["iv-card-sign-in"],L:[{F:"h2",X:"Want to vote?"},{F:"a",Y:["iv-card-sign-in-button","iv-button"],P:{href:U2(b.rj)},L:[{F:"span",Y:["iv-button-content"],X:"Sign in"}]}]}));f=new g.Q({F:"div",
Y:f,L:d});d=f.element;Uta(b,d);vta(a.o.o,d,g.Qa(a.B,b),a);(0,g.y)(g.ge("iv-card-poll-choice-input",d),function(h){this.o.o.na(h,"focus",g.Qa(this.u,!0));this.o.o.na(h,"blur",g.Qa(this.u,!1))},a);
b.rj&&(d=g.he("iv-card-sign-in-button",d),a.A(d,b.rj,b.id,b.Tb,b.Jc.click,5));return f},Wta=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.SO?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.tG&&b.Lw?{F:"span",Y:d,P:e,X:b.Lw}:"";c={F:"div",Y:["iv-card",c],L:[{F:"a",I:"iv-click-target",P:{href:U2(b.url)},L:[Z2(b.vj,d?{F:"div",I:"iv-card-image-text",L:[d,b.priceText]}:""),{F:"div",I:"iv-card-content",L:[{F:"h2",I:"iv-card-primary-link",X:b.title},$2(a,b)]}]}]};c=new g.Q(c);a3(a,g.ge("iv-click-target",c.element),b,b.url);return c},b3=function(a){return a.customMessage?
Y2("div","iv-card-message",a.customMessage):""},Z2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{F:"div",I:"iv-card-image",P:{style:c},L:d}},$2=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(Y2("li","",d))},a);
return{F:"ul",I:"iv-card-meta-info",L:c}},Tta=function(a,b){return{F:"li",
I:Ota(a,b.index),L:[{F:"label",L:[{F:"input",I:"iv-card-poll-choice-input",P:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{F:"span",I:"iv-card-poll-choice-text",L:[{F:"span",I:"iv-card-poll-choice-percent"},Y2("span",void 0,b.desc)]}]},{F:"div",I:"iv-card-poll-result",L:[{F:"div",I:"iv-card-poll-result-bar"}]}]}},Y2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&
(b={"class":b.join(" ")}):b={};
b.dir=g.Qn(c);return{F:a,P:b,X:c}},Xta=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.En&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.En+");");c.dir=g.Qn(a.customMessage);var d=[{F:"span",X:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",I:"iv-card-link-icon"}));return{F:"div",Y:b,P:c,L:d}},Uta=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.he(Ota(a,e.index),b);e=e.count/c;null==a.Fe&&(e=0);g.J(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Fe==d);f.getElementsByTagName("input")[0].checked=a.Fe==d;var h=Math.floor(100*e).toFixed(0),l=g.he("iv-card-poll-choice-percent",f);g.Ce(l,g.zM("$PERCENT%",{PERCENT:h}));f=g.he("iv-card-poll-result-bar",f);g.xh(f,"transform","scaleX("+e.toFixed(2)+")")}g.J(b,"iv-card-poll-voted",null!=a.Fe);g.J(b,"iv-card-poll-expanded",
null!=a.Fe&&1<a.choices.length)},a3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.A(e,d,c.id,c.Tb,c.Jc.click,5)},a)},Yta=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Zta=function(a,b){return b?b:Yta(a)?"current":"new"},c3=function(a,b){g.z.call(this);
var c=this;this.Ka=a;this.context=b;this.Iv=!1;this.fa=new Map;this.ma=new Map;this.context.K.addEventListener(g.jC("annotations_module"),function(d){(d=c.fa.get(d))&&d.apply(c)});
this.context.K.addEventListener("crx_annotations_module",function(d){(d=c.ma.get(d))&&d.apply(c)})},$ta=function(a,b,c,d,e){var f=U2(b);
if(f){var h=Zta(f,b.target),l=(0,g.x)(function(){b.o&&this.context.K.pauseVideo();var m=this.context.videoData.Qb||!1,n=g.fq(f||"");m&&n&&(n.v||n.list)?g.ET(this.context.K.app,n.v,c,n.list,!1,void 0):g.RN(f||"","current"==h?"_top":void 0,c)},a);
"new"==h&&(l(),l=null);W2(a.context.logger,d,l,e);Yta(f)||(a=g.Wr(),d=c.itct,a&&d&&g.qs(a,g.Pr(d)))}},aua=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},d3=function(a,b,c){return{By:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
GC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
zq:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},g3=function(a,b,c){c3.call(this,b,c);
var d=this;this.u=a;this.ca=this.Fa=this.C=this.Da=!1;this.ga=null;this.ba=new g.H(g.Ia,c.B.gb?4E3:3E3);g.A(this,this.ba);this.ya=new g.H(g.Ia);g.A(this,this.ya);this.H=new X2(c,(0,g.x)(this.Sk,this),(0,g.x)(this.Qo,this));this.V=new g.Q({F:"div",I:"iv-drawer",P:{id:"iv-drawer"},L:[{F:"div",I:"iv-drawer-header",P:{"aria-role":"heading"},L:[{F:"span",I:"iv-drawer-header-text"},{F:"button",Y:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",I:"iv-drawer-content"}]});
g.A(this,this.V);this.D=this.V.element;this.sa=new g.yN(this.V,330);g.A(this,this.sa);this.Ba=g.he("iv-drawer-header-text",this.D);this.B=g.he("iv-drawer-content",this.D);this.A=[];this.za=this.T=this.G=this.ea=this.o=null;this.W=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Fa&&e3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Fa=d.C)&&f3(d)});
this.N=this.J=this.aa=null;this.R=0},bua=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){e3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){f3(a)});
var c=b.data.headerText;g.Ce(a.Ba,c);a.T&&a.T.setAttribute("title",c);a.aa=g.Pr(b.data.trackingParams);a.N=g.Pr(b.data.closeTrackingParams);a.J=g.Pr(b.data.iconTrackingParams)},cua=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.R;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"simple",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Tb:h3(a,c,b,d),sponsored:!1,Jc:d3(d,e,d.command),fe:d.trackingParams?g.Pr(d.trackingParams):null,ae:e.trackingParams?
g.Pr(e.trackingParams):null,Dd:f&&f.trackingParams?g.Pr(f.trackingParams):null,imageUrl:i3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,En:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?T2({pause_on_navigation:!a.context.videoData.xa,target:"new",value:d.command.urlEndpoint.url}):null};j3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Tb:h3(a,c,b,d),sponsored:!1,Jc:d3(d,e,d.endpoint),fe:d.trackingParams?g.Pr(d.trackingParams):null,ae:e.trackingParams?g.Pr(e.trackingParams):null,Dd:f&&f.trackingParams?
g.Pr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.S(d.customText):null,OB:i3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:T2({pause_on_navigation:!a.context.videoData.xa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};j3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Tb:h3(a,c,b,d),sponsored:!1,Jc:d3(d,e,d.action),fe:d.trackingParams?g.Pr(d.trackingParams):null,ae:e.trackingParams?g.Pr(e.trackingParams):null,Dd:f&&f.trackingParams?g.Pr(f.trackingParams):
null,vj:i3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:T2({pause_on_navigation:!a.context.videoData.xa,target:"new",value:aua(d.action)})};j3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"video",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Tb:h3(a,c,b,d),sponsored:!1,Jc:d3(d,e,d.action),fe:d.trackingParams?g.Pr(d.trackingParams):null,ae:e.trackingParams?g.Pr(e.trackingParams):null,Dd:f&&f.trackingParams?g.Pr(f.trackingParams):null,vj:i3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.S(d.lengthString):null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:T2({pause_on_navigation:!a.context.videoData.xa,target:"new",value:aua(d.action)})};j3(a,c)}a.R++},i3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},h3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},eua=function(a,b){var c=dua(a,b);
c&&(c==a.o&&(a.o=null),a.u.removeCueRange(c.card.id),g.ye(c.Er),g.gb(a.A,c),a.Hn(),k3(a))},e3=function(a,b,c){if(!a.C){a.sa.show();
a.ea=new g.H(function(){g.I(a.context.K.getRootNode(),g.EM.IV_DRAWER_OPEN)},0);
a.ea.start();a.ga=g.ip(a.B,"mousewheel",(0,g.x)(a.JL,a));a.C=!0;var d=g.Wr();d&&a.aa&&a.N&&x2(d,[a.aa,a.N]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.az||(f.az=!0,Rta(a.context.logger,f.card.Jc.By,e));d&&x2(d,[f.card.fe])});
w2(a.u);c&&(a.G=new g.H(function(){a.va=a.T;a.za.focus()},330),a.G.start())}},f3=function(a){a.C&&(a.sa.hide(),g.jp(a.ga),a.ga=null,g.In(a.context.K.getRootNode(),g.EM.IV_DRAWER_OPEN),a.C=!1,w2(a.u),a.G&&a.G.stop(),a.G=new g.H(function(){a.va&&(a.va.focus(),a.va=null)},330),a.G.start())},fua=function(a){var b=g.he("iv-drawer-close-button",a.D);
a.context.o.na(b,"click",a.BE,a);a.context.o.na(a.B,"touchend",function(){a.ba.start()});
a.context.o.na(a.B,"scroll",a.OE,a);a.context.u.subscribe("onHideControls",function(){a.ca=!0});
a.context.u.subscribe("onShowControls",function(){a.ca=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.ca=g.Gn(a.u.getRootNode(),"ytp-autohide")});
a.W.push(g.To("iv-button-shown",a.AG,a));a.W.push(g.To("iv-button-hidden",a.zG,a));a.W.push(g.To("iv-teaser-shown",a.DG,a));a.W.push(g.To("iv-teaser-hidden",a.CG,a));a.W.push(g.To("iv-teaser-clicked",a.BG,a))},j3=function(a,b){a.Da||(g.Hn(a.wa(),[g.EM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]),g.CL(a.u,a.D,5),fua(a),a.T=g.he("ytp-cards-button",a.u.getRootNode()),a.za=g.he("iv-drawer-close-button",a.D),a.Da=!0);eua(a,b.id);var c=gua(a,b);if(c){var d={card:b,Er:c.element,az:!1},e=hua(a,d);g.ob(a.A,e,0,d);c.da(a.B,e);a.Hn();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Qa(a.nO,d)):(c=1E3*a.context.K.getCurrentTime(),5E3>c&&c>b.startMs&&a.tC(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Qa(a.tC,d)),k3(a))}},gua=function(a,b){switch(b.type){case "simple":var c=
a.H;
var d=b.displayDomain?{F:"div",I:"iv-card-image-text",X:b.displayDomain}:"";var e=Xta(b);d={F:"div",Y:["iv-card"],L:[{F:"a",I:"iv-click-target",P:{href:U2(b.url)},L:[Z2(b.imageUrl,d),{F:"div",I:"iv-card-content",L:[Y2("h2",void 0,b.title),e]}]}]};d=new g.Q(d);a3(c,g.ge("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={F:"div",Y:["iv-card","iv-card-channel"],L:[{F:"a",Y:["iv-click-target"],P:{href:U2(b.url),"data-ytid":b.channelId},L:[Z2(b.OB),{F:"div",I:"iv-card-content",
L:[b3(b),{F:"h2",I:"iv-card-primary-link",X:b.title},$2(c,b)]}]}]},d=new g.Q(d),a3(c,g.ge("iv-click-target",d.element),b,b.url),d;case "episode":return Wta(a.H,b,"iv-card-episode");case "movie":return Wta(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={F:"div",Y:["iv-card","iv-card-playlist"],L:[{F:"a",I:"iv-click-target",P:{href:U2(b.url)},L:[Z2(b.vj,{F:"div",I:"iv-card-image-overlay",L:[{F:"span",I:"iv-card-playlist-video-count",X:b.playlistVideoCount}]}),{F:"div",I:"iv-card-content",L:[b3(b),
Y2("h2","iv-card-primary-link",b.title),$2(c,b)]}]}]},d=new g.Q(d),a3(c,g.ge("iv-click-target",d.element),b,b.url),d;case "poll":return Vta(a.H,b);case "productListing":c=a.H;var f=!g.db(b.offers);d=["iv-card"];e="";var h=Xta(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],h=[],f.price&&h.push({F:"div",I:"iv-card-offer-price",X:f.price}),f.merchant&&h.push({F:"div",I:"iv-card-offer-merchant",X:f.merchant}),h={F:"div",L:h});d={F:"div",Y:d,P:{tabindex:"0"},L:[{F:"a",
Y:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+b.imageUrl+");",href:U2(b.url),"aria-hidden":"true",tabindex:"-1"}},{F:"div",I:"iv-card-content",L:[b.sponsored?{F:"div",I:"iv-card-sponsored",L:["Sponsored",{F:"div",I:"iv-ad-info-container",L:[{F:"div",I:"iv-ad-info",X:"{{adInfo}}"},{F:"div",I:"iv-ad-info-icon-container",L:[{F:"div",I:"iv-ad-info-icon"},{F:"div",I:"iv-ad-info-callout"}]}]}]}:"",{F:"a",I:"iv-click-target",P:{href:U2(b.url)},L:[Y2("h2",e,b.title),h]}]}]};d=new g.Q(d);
e=g.te("span");g.Ce(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.sb(e,"adInfo");a3(c,g.ge("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{F:"span",Y:["yt-badge","yt-badge-live"],X:"LIVE NOW"}:"",d={F:"div",Y:["iv-card","iv-card-video"],L:[{F:"a",I:"iv-click-target",P:{href:U2(b.url)},L:[Z2(b.vj,b.videoDuration?{F:"span",I:"iv-card-video-duration",X:b.videoDuration}:""),{F:"div",I:"iv-card-content",
L:[b3(b),Y2("h2","iv-card-primary-link",b.title),$2(c,b),d]}]}]},d=new g.Q(d),a3(c,g.ge("iv-click-target",d.element),b,b.url),d}return null},hua=function(a,b){if(0==a.A.length)return 0;
var c=g.$a(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},iua=function(a){return a.o?"productListing"==a.o.card.type:(0,g.yi)(a.A,function(b){return"productListing"==b.card.type})},k3=function(a){g.J(a.u.getRootNode(),"ytp-cards-shopping-active",iua(a))},jua=function(a,b){if(a.V.Ja()){var c=new C2([0,
a.B.scrollTop],[0,b.Er.offsetTop],600,pta);a.context.A.na(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.A.na(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.Ju(a.V,!0),a.B.scrollTop=b.Er.offsetTop,g.Ju(a.V,!1)},l3=function(a){return a.o&&a.o.card?a.o.card:a.A[0]&&a.A[0].card?a.A[0].card:null},dua=function(a,b){return g.Za(a.A,function(c){return c.card.id==b})},m3=function(a,b,c){c3.call(this,a,b);
this.annotation=c;this.isActive=!1},kua=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},n3=function(a,b,c){m3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.D=this.C=null},o3=function(a,b,c){m3.call(this,a,b,c);
this.J=this.C=this.R=!1;this.G=5E3;this.B=null;this.H=g.se("DIV","iv-promo-contents");this.u=this.A=this.o=null;this.D=new g.H(function(){this.o.setAttribute("aria-hidden",!0);g.Rh(this.A,!1);g.Rh(this.u,!0)},700,this);
g.A(this,this.D)},lua=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.wa().setAttribute("aria-hidden",!0);a.wa().setAttribute("aria-label","Promotion");a.wa().tabIndex=0;var e=a.annotation.qc(),f=b.image_url;if(f){var h=g.se("DIV",["iv-promo-img","iv-click-target"]);f=g.se("IMG",{src:f,"aria-hidden":"true"});h.appendChild(f);b.video_duration&&!b.is_live?(f=g.se("SPAN","iv-promo-video-duration",
b.video_duration),h.appendChild(f)):b.playlist_length&&(f=g.se("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),h.appendChild(f));e&&a.Sk(h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.se("A","iv-promo-txt"),g.bd(f,U2(e)),a.o=f):a.o=g.se("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.se("P",null,g.se("STRONG",null,b.text_line_1));var m=g.se("P",null,g.se("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.O(a.context.B.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.se("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.se("BUTTON",["iv-button","iv-promo-button"],g.se("SPAN","iv-button-content",f));var q=g.se("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Sk(a.wa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&a.Sk(a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.se("P",
null,g.se("SPAN",null,b.text_line_1)),m=g.se("P",null,g.se("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.se("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.I(a.o,"iv-click-target"),e&&a.Sk(a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);q&&a.H.appendChild(q);c=g.se("DIV","iv-promo-actions");a.u=g.se("BUTTON",["iv-promo-expand","ytp-button"]);a.u.title="Expand";a.context.o.na(a.u,"click",g.Qa(a.Os,
5E3),a);c.appendChild(a.u);g.Rh(a.u,!1);a.context.o.na(a.wa(),"mouseover",a.KF,a);a.context.o.na(a.wa(),"mouseout",a.JF,a);a.context.o.na(a.wa(),"touchend",g.Qa(a.Os,5E3),a);a.A=g.se("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.na(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.CF:a.BF,a);c.appendChild(a.A);g.Hn(a.wa(),d);h&&(a.wa().appendChild(h),n&&h.appendChild(n));a.wa().appendChild(a.H);a.wa().appendChild(c)},mua=function(a){a.C||a.J||a.B||(g.I(a.wa(),"iv-promo-collapsed"),
a.C=!0,a.D.start())},nua=function(a){a.D.stop();
a.C&&(g.Jn(a.wa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Rh(a.u,!1),g.Rh(a.A,!0))},oua=function(a,b){a.B||(a.B=g.Yf(function(){p3(this);
mua(this)},b,a))},p3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},q3=function(a){g.OL.call(this,a);
this.R=!1;this.J=0;this.G={};this.W=new Qta(a);this.C=new g.zr(this);g.A(this,this.C);this.D=this.A=null;this.C.M(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.C.M(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.C.M(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.C.M(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.C.M(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.eM,this);this.subscribe("resize",this.Op,this);this.player.O().J.subscribe("vast_info_card_add",this.AB,this);this.V=new g.zr(this);g.A(this,this.V);this.T=g.se("DIV","video-custom-annotations");this.u=new g.Q({F:"div",Y:["ytp-player-content","ytp-iv-player-content"]});g.A(this,this.u);g.CL(this.player,this.u.element,4);this.u.hide();this.B=new g.Q({F:"div",Y:["ytp-iv-video-content"]});g.A(this,this.B);g.ve(this.B.element,g.se("DIV","video-annotations",
this.T));this.H=this.o=null;this.N=[];pua(this)&&this.load();var b=g.te("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ke(this,function(){g.ye(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},qua=function(){var a=g.se("DIV",["annotation",
"annotation-type-custom"]);g.Rh(a,!1);return a},rua=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},pua=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.nD||b.J.get(a.videoId)||g.JB(a)||g.KB(a)?!0:!1},sua=function(a,b){var c=!b.isCued()&&!g.U(b,1024);
g.Ju(a.u,c);g.Ju(a.B,c)},tua=function(a,b,c){a.R=!0;
a.D=g.xq(b,c)},uua=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(uua(a,e))}return c},vua=function(a,b,c){return!(a.loaded&&a.J==b&&a.player.getVideoData().videoId==
c)},yua=function(a){var b=a.player.getVideoData();
if(b.de){var c=a.player.O().J.get(b.videoId);if(c){var d={format:"XML",be:{},method:"POST",withCredentials:!0};d.qd=(0,g.x)(function(e,f,h){vua(this,e,f)||(e=g.rq(h)&&h.responseXML?h.responseXML:null)&&r3(this,e)},a,a.J,b.videoId);
g.zp()&&(d.qd=wua(a,d.qd));d.tb={ic_only:"1"};xua(d,c);a.R=!0;g.xq(b.de,d)}}},xua=function(a,b){a.method="POST";
a.tb=a.tb||{};b.Ln&&(a.tb.ic_coll=b.Ln);b.Mn&&(a.tb.ic_xml=b.Mn);b.dn&&(a.tb.ic_track=b.dn)},zua=function(a){var b=new g.Q({F:"div"});
g.Rh(b.element,!1);var c=new g3(a.player,b.element,s3(a));g.A(c,b);b.da(a.u.element);c.Sm();return c},s3=function(a){if(!a.H){var b=new F2(a);
g.A(a,b);var c=new g.w1(a);g.A(a,c);a.H=new Sta(b,c,a.player.O(),a.player.getVideoData(),a.W,a.player,a.Wh)}return a.H},r3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Wr();if(e){var f=g.Ur();f&&g.ks(g.Co("use_default_events_client")?void 0:g.Jq,e,f,[g.Pr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=uua(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=S2(h.type,Aua),t=S2(h.style,Bua),u=R2(h.data),w=0!=u.length?JSON.parse(u):{},B=Gta(h.action);f=n&&q?new V2(n,q,t,B,w):null}else f=null}catch(aa){}if(f){a:{switch(f.type){case "branding":case "promotion":h=
!0;break a}h=!1}if(h){h=a;m=f;var D=qua(),E=null;switch(m.type){case "branding":if(h.player.O().Da)break;h.u.element.appendChild(D);E=new n3(D,s3(h),m);break;case "promotion":g.CL(h.player,D,4),E=new o3(D,s3(h),m)}E&&E.Sm();if(h=E)g.A(a,h),a.G[f.id]=h}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=zua(a),g.A(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(h=f.data.tracking||{},h={By:h.impression,click:h.click,close:h.close,GC:h.teaser_impression,zq:h.teaser_click},m=
f.data.tracking_params||{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Tb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:h,fe:m.card?g.Pr(m.card):null,ae:m.teaser?g.Pr(m.teaser):null,Dd:m.icon?g.Pr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,OB:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:T2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};j3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Tb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:h,fe:m.card?g.Pr(m.card):null,ae:m.teaser?g.Pr(m.teaser):null,
Dd:m.icon?g.Pr(m.icon):null,vj:f.data.image_url,Lw:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,tG:!!f.data.is_paygated,SO:!!f.data.user_has_entitlement,url:T2({target:f.data.target||"new",value:f.data.url})};j3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Tb:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Jc:h,fe:m.card?g.Pr(m.card):null,ae:m.teaser?g.Pr(m.teaser):null,Dd:m.icon?g.Pr(m.icon):null,vj:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:T2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};j3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Tb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:h,fe:m.card?g.Pr(m.card):null,ae:m.teaser?g.Pr(m.teaser):null,Dd:m.icon?g.Pr(m.icon):null,title:f.data.title,choices:f.data.choices,Fe:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,rj:f.data.signin_url?T2({target:"current",value:f.data.signin_url}):null,dP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};j3(c,f);break;case "productListing":f.data.signin_url&&
(D=T2({target:"current",value:f.data.signin_url}));E=[];for(var F=f.data.offers||[],G=0;G<F.length;G++)E.push(new Pta(g.jd(F[G].merchant),g.jd(F[G].price)));f={hU:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Tb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:h,fe:m.card?g.Pr(m.card):null,ae:m.teaser?g.Pr(m.teaser):null,Dd:m.icon?g.Pr(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,En:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:T2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),rj:D,DU:f.data.signin_title?f.data.signin_title:null,CU:f.data.signin_message?f.data.signin_message:null,offers:E};j3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Tb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:h,fe:m.card?g.Pr(m.card):null,ae:m.teaser?g.Pr(m.teaser):null,Dd:m.icon?g.Pr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,En:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:T2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};j3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Tb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:h,fe:m.card?g.Pr(m.card):null,ae:m.teaser?
g.Pr(m.teaser):null,Dd:m.icon?g.Pr(m.icon):null,vj:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:T2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},j3(c,f)}}else bua(a.o,f);c=!0}}}c&&(w2(a.player),a.Op())},Cua=function(a,b){var c=!1;
a.o||(a.o=zua(a),g.A(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())cua(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.Ce(c.Ba,d),c.T&&c.T.setAttribute("title",d),c.aa=b.trackingParams?g.Pr(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.Pr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.Pr(b.icon.infoCardIconRenderer.trackingParams):null,w2(a.player),a.Op())},
Dua=function(a,b,c,d,e){if(!a.player.O().Da){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Kta("openUrl","click",new Ita("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:h,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new V2(c,"branding","branding",f,d);d=qua();a.u.element.appendChild(d);f=new n3(d,s3(a),f);f.Sm();g.A(f,f);a.G[c]=f}},wua=function(a,b){return(0,g.x)(function(){if(!this.ha()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Qa.apply(window,c);this.N.push(g.xp(b))}},a)},z2={},A2=null;g.Sa(C2,g.Kn);g.k=C2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.fb())return!1;B2(this);this.startTime=a=(0,g.C)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.Lp();this.xe("play");-1==this.o&&this.xe("resume");this.o=1;var b=g.Pa(this);b in z2||(z2[b]=this);rta();sta(this,a);return!0};
g.k.stop=function(a){B2(this);this.o=0;a&&(this.progress=1);tta(this,this.progress);this.xe("stop");this.Fm()};
g.k.pause=function(){this.fb()&&(B2(this),this.o=-1,this.xe("pause"))};
g.k.Z=function(){0==this.o||this.stop(!1);this.xe("destroy");C2.Nb.Z.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.qu=function(){this.xe("animate")};
g.k.xe=function(a){this.dispatchEvent(new uta(a,this))};
g.Sa(uta,g.Ne);g.Sa(D2,C2);D2.prototype.B=g.Ia;D2.prototype.qu=function(){this.B();D2.Nb.qu.call(this)};
D2.prototype.Fm=function(){this.B();D2.Nb.Fm.call(this)};
D2.prototype.Lp=function(){this.B();D2.Nb.Lp.call(this)};
g.Sa(E2,D2);E2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(F2,g.z);F2.prototype.na=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.ip(a,b,c);this.o.push(a);return a};
F2.prototype.wt=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.sp(a,b,c);this.o.push(a);return a};
F2.prototype.eb=function(a){g.jp(a);g.gb(this.o,a)};
F2.prototype.Z=function(){g.jp(this.o);this.o.length=0;g.z.prototype.Z.call(this)};g.r(J2,g.OL);g.k=J2.prototype;g.k.load=function(){g.OL.prototype.load.call(this);if(!K2(this)){var a=g.IB(this.player.getVideoData());if(a)a=I2(a,xta(this)),L2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",qd:(0,g.x)(this.ZK,this,a),be:{v:a},withCredentials:!0};this.R&&(a.be.ptype="embedded");var c=this.player.getVideoData().Xn;c&&(a.tb={ad_tracking:c});if(b=g.HB(b))if(b=g.Bc(b),b=g.zc(b))this.B=g.xq(b,a)}}};
g.k.unload=function(){L2(this,null);this.B&&(this.B.abort(),this.B=null);g.OL.prototype.unload.call(this)};
g.k.Sc=function(a,b){if(!K2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=I2(b,"new");L2(this,c);return!0}return null};
g.k.getOptions=function(){return K2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.ZK=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=I2(c,xta(this)))}L2(this,c)};
g.k.vz=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Eua.length;f++){var h=Math.abs(b.width-Eua[f]);if(-1==e||d>=h)e=f,d=h}d=Fua[e];this.A&&g.xh(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Ph(e.element,Math.round(h.width*a.width),f);g.Fh(e.element,m,n);g.Jn(e.element,Gua);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Jn(e.element,Fua);g.I(e.element,d);(e=g.fe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.xh(e,"height",f+"px")}}}}};
g.k.gH=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())P2(this,this.u.impressionUrls),(a=g.Wr())&&this.u.visualElement&&g.ls(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");P2(this,c.impressionUrls);(b=g.Wr())&&g.ls(b,c.visualElement);this.player.O().A&&this.player.ra("endscreenelementshown",a)}};
g.k.hH=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.In(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.In(b,"ytp-ce-shown");this.player.O().A&&this.player.ra("endscreenelementhidden",a)}};
g.k.yN=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.Jn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.QA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Gn(c,"ytp-ce-element");){g.Gn(c,"subscribe-label")&&Q2(this,a);if(g.Gn(c,"ytp-ce-channel-subscribe"))return;c=g.Ae(c)}if(!c||g.Gn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.vu(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.DO?(Q2(this,a),this.sC(),this.player.pauseVideo(),c=g.Bc(N2(this,a.targetUrl)),c=g.zc(c),g.RN(c,void 0,a.Tb)):(c=this.player.getVideoData().Qb,
c=(0,g.x)(this.vO,this,c,N2(this,a.targetUrl),a.Tb),c=(0,g.x)(this.sC,this,c),Q2(this,a,c))}}};
g.k.vO=function(a,b,c){var d=g.fq(b);a&&d&&(d.v||d.list)?g.ET(this.player.app,d.v,c,d.list,!1,void 0):g.QN(b,c)};
g.k.Ht=function(a,b){g.Gn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.H(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),P2(this,b.iG),O2(this,b.id,!0))};
g.k.vu=function(a,b){g.In(a.element,"ytp-ce-element-hover");g.In(a.element,"ytp-ce-force-expand");O2(this,b.id,!1)};
g.k.sC=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Eua=[346,426,470,506,570,640,853,1280,1920],Fua="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Gua=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Jta={uQ:"current",hS:"new"};var Lta={CLOSE:"close",kS:"openUrl",bE:"subscribe"},Mta={jQ:"click",CLOSE:"close",nR:"hidden",WS:"rollOut",XS:"rollOver",dT:"shown"};V2.prototype.qc=function(){var a=Nta(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var Bua={MP:"anchored",DD:"branding",CHANNEL:"channel",tQ:"cta",qR:"highlightText",IR:"label",PLAYLIST:"playlist",HS:"popup",jT:"speech",bE:"subscribe",vT:"title",VIDEO:"video",LT:"website"},Aua={DD:"branding",aQ:"card",BQ:"drawer",pR:"highlight",TR:"marker",MS:"promotion",TEXT:"text",OT:"widget"};X2.prototype.u=function(a,b){var c=g.He(b.target,"label");c&&g.J(c,"iv-card-poll-choice-focused",a)};
X2.prototype.B=function(a,b){var c=g.He(b.target,null,"iv-card-poll",void 0);if(c)if(a.rj)g.he("iv-card-sign-in-button",c).click();else{var d=parseInt(nta(b.target),10);if(null==a.Fe)a.choices[d].count++,a.Fe=d;else if(a.Fe!=d){var e=a.choices[a.Fe];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Fe=d}else e=a.choices[a.Fe],e.count=Math.max(e.count-1,0),a.Fe=null;Uta(a,c);g.Bq(this.o.videoData.de,{be:{action_poll_vote:1},tb:{poll_id:a.id,index:d,session_token:a.dP}});W2(this.o.logger,a.Jc.click,
void 0,5);(c=g.Wr())&&a.fe&&g.qs(c,a.fe)}};g.r(c3,g.z);g.k=c3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.gC(a,b,{id:c});a.namespace="annotations_module";d&&this.fa.set(a,d);e&&this.ma.set(a,e);g.yL(this.context.K,[a])};
g.k.Sm=function(){this.context.u.subscribe("resize",this.Hn,this)};
g.k.wa=function(){return this.Ka};
g.k.Sk=function(a,b,c,d,e,f){this.context.o.na(a,"click",g.Qa(this.Qo,b,c,d,e||[],f||0),this);this.context.o.na(a,"touchstart",g.Qa(function(){this.Iv=!1}),this);
this.context.o.na(a,"touchmove",g.Qa(function(){this.Iv=!0}),this)};
g.k.Qo=function(a,b,c,d,e,f){if(this.Iv)return!1;f&&(f.stopPropagation(),f.preventDefault());$ta(this,a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ye(this.wa())};
g.k.Hn=function(){};
g.k.Z=function(){this.fa.clear();this.ma.clear();g.z.prototype.Z.call(this)};g.r(g3,c3);g.k=g3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.u.getRootNode())?(a=g.Qh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Hn=function(){var a=this.isAvailable();g.Rh(this.wa(),a);g.J(this.context.K.getRootNode(),g.EM.IV_DRAWER_ENABLED,a);w2(this.u)};
g.k.destroy=function(){var a=g.qL(g.dL(this.u));a&&a.Dt(!1,void 0);try{this.u.getRootNode().removeChild(this.D)}catch(b){}g.Uo(this.W);g.jp(this.ga);this.ea&&this.ea.dispose();this.G&&this.G.dispose();c3.prototype.destroy.call(this)};
g.k.JL=function(a){this.ba.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.k.tC=function(a){if(!g.Gn(this.u.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.Wr(),c=this.o?this.o.card.Dd:this.J;b&&c&&y2(b,[c]);this.o=a;k3(this)}if(b="none"!=this.wa().style.display)2==this.context.K.getPresentingPlayerType()?b=1==this.context.K.getAdState():(b=this.context.K.getPlayerState(),c=0==b&&0===this.context.K.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.qL(g.dL(this.u)))&&c.Dt(!0,
b));this.ya.isActive()||((!this.C||!this.ba.isActive()&&this.ca)&&jua(this,a),this.ya.start(910+a.card.teaserDurationMs))}};
g.k.nO=function(a){this.C||(this.o=a,k3(this),jua(this,a),e3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.k.BE=function(){if(this.C){W2(this.context.logger,l3(this).Jc.close);var a=g.Wr();a&&this.N&&g.qs(a,this.N);f3(this)}};
g.k.OE=function(){g.J(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.AG=function(){var a=g.Wr(),b=l3(this);b=b?b.Dd:this.J;a&&b&&x2(a,[b])};
g.k.zG=function(){var a=g.Wr(),b=l3(this);b=b?b.Dd:this.J;a&&b&&y2(a,[b])};
g.k.DG=function(){var a=l3(this);W2(this.context.logger,a.Jc.GC);var b=g.Wr();b&&a&&x2(b,[a.ae,a.Dd])};
g.k.CG=function(){var a=g.Wr(),b=l3(this);a&&b&&y2(a,[b.ae])};
g.k.BG=function(a){var b=l3(this),c=g.Wr();this.o?a?(a=this.context.logger,W2(a,b.Jc.zq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.ae&&g.qs(c,b.ae)):(a=this.context.logger,W2(a,b.Jc.zq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Dd&&g.qs(c,b.Dd)):(a=this.context.logger,W2(a,b.Jc.zq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.qs(c,this.J))};g.r(m3,c3);m3.prototype.Sm=function(){c3.prototype.Sm.call(this);kua(this)};
m3.prototype.show=function(){c3.prototype.show.call(this);var a=g.Wr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&x2(a,[g.Pr(b.itct)])};
m3.prototype.hide=function(){c3.prototype.hide.call(this);var a=g.Wr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&y2(a,[g.Pr(b.itct)])};g.r(n3,m3);g.k=n3.prototype;g.k.wO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Qh(a);this.o||(g.Oh(a,e.width),g.Oh(b,e.width));g.xh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.xh(c,"right","1px");this.B=!0;g.Rh(a,!0);this.C=new g.H(function(){g.I(this.wa(),"iv-branding-active")},0,this);
this.C.start()}};
g.k.gG=function(a,b){g.In(this.wa(),"iv-branding-active");this.D=new g.H((0,g.x)(function(){g.Rh(a,!1);this.o||g.Oh(b,0)},this),250);
this.D.start();this.B=!1};
g.k.show=function(){if(!this.isActive){m3.prototype.show.call(this);if(!this.G){g.I(this.wa(),"iv-branding");var a=this.annotation.data;this.u=g.se("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Rh(this.u,!1);var b=g.se("DIV","branding-img-container",this.u);this.wa().appendChild(b);(b=this.annotation.qc())&&this.Sk(this.u,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.se("DIV","iv-branding-context-name");
g.Ce(c,a.channel_name);var d=g.se("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=new g.fR(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.K),this.o.da(d);b=g.se("DIV","iv-branding-context-subscribe-caret");c=g.se("DIV","branding-context-container-inner",b,c,d);g.Rh(c,!1);d=g.se("DIV","branding-context-container-outer",c);g.xh(d,"right",
a.image_width+"px");this.wa().appendChild(d);this.A=new g.H(g.Qa(this.gG,c,d),500,this);g.A(this,this.A);this.context.o.na(this.wa(),"mouseover",(0,g.x)(this.wO,this,c,d,b,a.image_height));this.context.o.na(this.wa(),"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Rh(this.wa(),!0);this.isActive=!0;if(this.u){a=this.u;var e=void 0===e?0:e;b=g.Jh(a);c=g.Qh(a);b=(new g.uh(b.x,b.y,c.width,c.height)).width;g.Fh(a,b);e=new E2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,ota);g.A(this,e);this.context.A.na(e,
"begin",g.Qa(g.Rh,a,!0));e.play()}}};
g.k.hide=function(){this.isActive&&(m3.prototype.hide.call(this),g.Rh(this.wa(),!1),this.isActive=!1)};
g.k.destroy=function(){this.o&&(this.o.dispose(),this.o=null);m3.prototype.destroy.call(this)};g.r(o3,m3);g.k=o3.prototype;g.k.show=function(){this.isActive||(m3.prototype.show.call(this),this.R||(lua(this),this.R=!0),g.Rh(this.wa(),!0),g.Yf(function(){g.In(this.wa(),"iv-promo-inactive")},100,this),this.wa().removeAttribute("aria-hidden"),this.isActive=!0,p3(this),nua(this),oua(this,this.G))};
g.k.hide=function(){this.isActive&&(g.I(this.wa(),"iv-promo-inactive"),this.isActive=!1,this.wa().setAttribute("aria-hidden",!0))};
g.k.Qo=function(a,b,c,d,e,f){return this.C?!1:m3.prototype.Qo.call(this,a,b,c,d,e,f)};
g.k.Os=function(a,b){b.stopPropagation();nua(this);oua(this,a);this.o.focus()};
g.k.KF=function(a){this.J=!0;this.Os(500,a)};
g.k.JF=function(){this.J=!1;mua(this)};
g.k.BF=function(a){a.stopPropagation();this.hide()};
g.k.CF=function(a){a.stopPropagation();p3(this);this.C=!0;g.I(this.wa(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();m3.prototype.destroy.call(this)};g.r(q3,g.OL);g.k=q3.prototype;g.k.Sc=function(a,b){if(!rua(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.v1(b);c&&r3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(eua(this.o,b),w2(this.player)),!0}return null};
g.k.getOptions=function(){return rua(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Op=function(){if(this.B){var a=g.jL(this.player).getVideoContentRect(!0);g.Ph(this.B.element,a.width,a.height);g.Fh(this.B.element,a.left,a.top)}if(this.o){var b=g.tL(this.player);a=this.o;b=b.width;g.J(a.D,"iv-drawer-small",426>=b);g.J(a.D,"iv-drawer-big",1280<=b)}};
g.k.eM=function(a){sua(this,a.state);g.U(a.state,2)&&(this.mm()&&this.lz()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Dt(!1))};
g.k.load=function(){g.OL.prototype.load.call(this);sua(this,g.iL(this.player));this.J++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.bL,this,b,this.J),d=(0,g.x)(function(){this.D=null},this);
g.zp()&&(c=wua(this,c));c={format:"XML",qd:c,onError:d,be:{}};a.isPharma&&(c.be.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().J.get(b))&&xua(c,b);b=b&&(b.Mn||b.Ln);if(!a.An||b)a.de?tua(this,a.de,c):(this.A=(0,g.x)(this.fH,this,c),this.player.addEventListener("videodatachange",this.A));g.CL(this.player,this.B.element,4);this.Op();(b=g.JB(a))&&Cua(this,b);(b=g.KB(a))&&b.featuredChannel&&Dua(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.k.fH=function(a){var b=this.player.getVideoData();b.de&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),tua(this,b.de,a))};
g.k.unload=function(){g.BR(this.player.app,"annotations_module",void 0);g.Bb(this.G,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,w2(this.player));this.R=!1;this.D&&(this.D.abort(),this.D=null);this.G={};this.u.hide();g.OL.prototype.unload.call(this);g.Gu(this.B);this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.bL=function(a,b,c){this.D=null;!vua(this,b,a)&&(a=g.rq(c)&&c.responseXML?c.responseXML:null)&&(r3(this,a),g.I(this.player.getRootNode(),"iv-module-loaded"))};
g.k.AB=function(a){a==this.player.getVideoData().videoId&&(this.loaded?yua(this):this.load())};
g.k.mm=function(){return!!this.o&&this.o.isAvailable()};
g.k.lz=function(){this.mm();return!!this.o&&this.o.C};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.mm();this.o&&(a?c?e3(this.o,c,b):e3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):f3(this.o))};
g.k.Dt=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.Z=function(){this.player.O().J.unsubscribe("vast_info_card_add",this.AB,this);g.In(this.player.getRootNode(),g.EM.IV_DRAWER_OPEN);for(var a=this.N,b=0,c=a.length;b<c;b++)g.Ap(a[b]);this.N.length=0;g.OL.prototype.Z.call(this)};g.cM.annotations_module=q3;g.cM.creatorendscreen=J2;})(_yt_player);
