(function(g){var window=this;var w3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.Js(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},x3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},Hua=function(a,b){var c=new g.Is;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},Iua=function(){this.u=[];
this.o=[]},y3=function(a,b){switch(b.kind){case "asr":Jua(b,a.u);
break;default:Jua(b,a.o)}},Jua=function(a,b){g.Za(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},z3=function(){g.z.call(this);
this.u=new Iua;this.B=[]},A3=function(a,b,c){z3.call(this,a);
this.audioTrack=c;this.o=null;this.B=b.Rw},B3=function(){this.segments=[]},Kua=function(a,b){var c=g.rb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.fb(a.segments,c),g.fb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ob(a.segments,c,0,b),g.ob(a.segments,c+1,0,b)))},C3=function(a,b,c,d,e,f){g.z.call(this);
this.policy=a;this.player=b;this.R=c;this.D=d;this.C=e;this.H=f;this.J=this.player.O();this.B=new B3;this.u=this.A=this.o=null;this.G=new g.H(this.Zy,1E3,this);this.events=new g.zr(this);g.A(this,this.G);g.A(this,this.events);this.events.M(b,"SEEK_COMPLETE",this.tB);this.tB();this.Zy()},Lua=function(a,b){var c=g.jx(b,a.policy,{}).qc(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.br(c,d,3,100).then(function(e){a.ha();var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.Gx(e);h?(e=g.jx(a.A,a.policy,{}),f=a.A,g.fx(f.u,e,h),f.requestId=e.get("req_id"),Lua(a,a.A)):(f||null==a.D||(h=a.A.o[0],a.C?a.D(e.response,1E3*(h.startTime+a.player.Bb())):a.D(e.responseText,1E3*(h.startTime+a.player.Bb()))),a.A=null,a.u=null)});
a.A=b;Kua(a.B,a.A.o[0].u)},D3=function(a,b){z3.call(this,b.O());
this.ka=a;this.K=b;this.o=null;this.A=!1;this.C=g.hz(this.K.O())&&!this.ka.u},Mua=function(a,b){var c=[],d;
for(d in a.ka.o)if(a.ka.o.hasOwnProperty(d)){var e=a.ka.o[d];if(g.PL(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Is({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Nua=function(a,b){return null!=b&&b in a.ka.o?a.ka.o[b]:null},Oua=function(a,b,c){var d=[],e;
for(e in a.ka.o)if(a.ka.o.hasOwnProperty(e)){var f=a.ka.o[e];if(g.PL(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},E3=function(a,b,c,d,e){z3.call(this,e||null);
this.videoId=b;this.Cy=d;this.C={};this.o=null;b=c||g.fq(a).hl||"";b=b.split("_").join("-");this.A=g.hq(a,{hl:b})},F3=function(a,b,c,d,e,f,h){var l={};
g.Ra(l,b);g.Ra(l,a.params);g.Ra(l,c);var m={};g.Ra(m,b.Cb);a.params.Cb&&g.Ra(m,a.params.Cb);g.Ra(m,c.Cb);l.Cb=m;g.Q.call(this,{F:"div",I:"caption-window",P:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},L:[{F:"span",I:"captions-text",P:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.V=!1;this.A=a;this.ba=this.W=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.G=null;this.maxWidth=.96*e;this.va=.96*f;this.u=l;
this.Da=c;this.C=this.o["captions-text"];this.za=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.aa=d/360*16;this.type=0;this.fa=this.aa*Pua(m);a=new g.Fr(this.element,!0);g.A(this,a);a.subscribe("dragstart",this.VK,this);a.subscribe("dragmove",this.UK,this);a.subscribe("dragend",this.SK,this);this.sa=this.ma=0;b="";this.u.windowOpacity&&(a=g.u1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+
")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":Qua[this.u.textAlign]};this.za&&(a["border-radius"]=b?this.fa/8+"px":"");if(this.B=2===this.A.params.o||3===this.A.params.o)b=this.element,c="vertical-rl",1===this.u.A&&(c="vertical-lr"),g.me&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.xh(b,"-o-writing-mode",c),g.xh(b,"-webkit-writing-mode",c),g.xh(b,"writing-mode",c),g.xh(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.A.params.o&&(g.xh(b,"text-orientation",
""),g.xh(b,"transform","rotate(180deg)"));g.xh(this.element,a);switch(this.u.Ne){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},Pua=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Rua=function(a,b){var c={},d=b.background?b.background:a.u.Cb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Cb.backgroundOpacity;d=g.u1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.za&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*Pua(b)+"px";d=1;e=b.color||a.u.Cb.color;if(b.color||null!=b.textOpacity)e=g.u1(e),d=null==b.textOpacity?a.u.Cb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.Gr&&(h=e=b.Gr);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ll()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Cb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.bf&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.fG&&(c.visibility="hidden");1===b.zy&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.kz||g.lz,3===a.A.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.tf||2===b.tf||3===b.tf||4===b.tf||5===b.tf)if(g.kz)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.tf){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Sua=function(a){a.G=g.te("SPAN");
g.xh(a.G,{display:"block"});g.I(a.G,"caption-visual-line");a.C.appendChild(a.G)},Tua=function(a,b){var c=g.te("SPAN");
g.xh(c,{display:"inline-block","white-space":"pre-wrap"});g.xh(c,Rua(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.xh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.xh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Uua=function(a,b,c){a.V=a.V||!!c;
var d={};g.Ra(d,a.u.Cb);g.Ra(d,c||b.o);g.Ra(d,a.Da.Cb);(c=!a.G)&&Sua(a);for(var e=a.W&&a.ba&&g.Qb(d,a.ba)?a.W:Tua(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(Sua(a),e=Tua(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.ue(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.kz||!g.Bh(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Bh(n.children[2],"text-emphasis-position")&&(m=a.B?"padding-left":"padding-bottom"),
g.oe?g.xh(e,m,"1em"):g.xh(e,m,"0.5em")))}a.ba=d;a.W=e;a.D.push(b)},G3=function(a,b,c,d,e,f,h){F3.call(this,a,b,c,d,e,f,h);
this.type=1},H3=function(a,b,c,d,e,f,h){F3.call(this,a,b,c,d,e,f,h);
this.type=2;this.H=[];this.N=this.J=this.ca=0;this.T=NaN;this.ya=0;this.Ba=null;this.ea=new g.H(this.EM,433,this);g.I(this.element,"ytp-caption-window-rollup");g.A(this,this.ea);g.xh(this.element,"overflow","hidden")},Vua=function(a,b){return(a.B?b.offsetHeight:b.offsetWidth)+1},Wua=function(a){if(isNaN(a.T)){var b=a.u.eh;
if(b){var c=g.te("SPAN");g.Ce(c,"\u2013".repeat(b));g.xh(c,Rua(a,a.u.Cb));a.C.appendChild(c);a.T=c.offsetWidth;a.C.removeChild(c)}else a.T=0}return a.T},Xua=function(a,b){if(!b)return"";
a.B&&1!==a.A.params.A&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},Yua=function(a){a.H=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.A.params.u,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.J=d;a.N=Math.max(Wua(a),a.ya,Vua(a,a.C))},Zua=function(a,b){Yua(a);
var c=a.H.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.J-c;if(c!==a.ca){var d=0<c&&0===a.ca;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),a.ea.Wa());g.xh(a.C,"transform",Xua(a,c));a.ca=c}Yua(a)},I3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.gC.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=h},J3=function(a,b,c,d,e){g.gC.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},$ua=function(a){var b="_"+K3++;
return new J3(0,0x8000000000000,0,b,a)},bva=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Yb){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[q.getAttribute("p")];l=ava(l.textContent,n.textContent,q.textContent,f.textContent,h);return new I3(a,b,e,c,l,d,m)}switch(m.Yb){case 9:case 10:m.tf=1;break;case 11:m.tf=2;break;case 12:m.tf=3;break;case 13:m.tf=4;break;case 14:m.tf=5}return new I3(a,b,e,c,l.textContent||"",d,m)},ava=function(a,b,c,d,e){var f=g.ll(),h=
f?g.te("DIV"):g.te("RUBY"),l=g.te("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.te("DIV"):g.te("RP");a.textContent=b;h.appendChild(a);b=f?g.te("DIV"):g.te("RT");b.textContent=c;h.appendChild(b);c=e.Yb;if(10===c||11===c||12===c||13===c||14===c)if(g.xh(b,"text-emphasis-style","filled circle"),g.xh(b,"text-emphasis-color","currentcolor"),g.xh(b,"webkit-text-emphasis","filled circle"),11===e.Yb||13===e.Yb)g.xh(b,"webkit-text-emphasis-position","under left"),g.xh(b,"text-emphasis-position","under left");c=!0;if(4===e.Yb||7===e.Yb||12===e.Yb||
14===e.Yb)g.xh(h,"ruby-position","over"),g.xh(h,"-webkit-ruby-position","before");else if(5===e.Yb||6===e.Yb||11===e.Yb||13===e.Yb)g.xh(h,"ruby-position","under"),g.xh(h,"-webkit-ruby-position","after"),c=!1;e=f?g.te("DIV"):g.te("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.xh(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.xh(f,"display","none"),f=f.nextElementSibling,g.xh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.xh(h.lastElementChild,"display","none"),d?(g.xh(h,"padding-top","0.6em"),g.xh(f,"top","0")):(g.xh(h,"padding-bottom","0.6em"),g.xh(f,"bottom","0")));return h},L3=function(){g.z.apply(this,arguments)},M3=function(a){L3.call(this);
this.D=a;this.B={};this.J={};this.R={};this.C="_"+K3++;this.H={};this.u=this.o=null;this.G=!0},N3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},O3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},P3=function(a,b){var c=N3(a,b);
return void 0!==c?c:null},R3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Q3.test(c),c},cva=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.R[d]:a.D);d=P3(b,"mh");null!=d&&(c.mk=d);d=P3(b,"ju");null!=d&&(c.textAlign=d);d=P3(b,"pd");null!=d&&(c.o=d);d=P3(b,"sd");null!=d&&(c.A=d);d=R3(b,"wfc");null!=d&&(c.windowColor=d);d=N3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},dva=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.J[d]);d=P3(b,"ap");null!=d&&(c.Ne=d);d=N3(b,"cc");null!=d&&(c.eh=d);d=N3(b,"ah");null!=d&&(c.ke=d);d=N3(b,"rc");null!=d&&(c.u=d);d=N3(b,"av");null!=d&&(c.vf=d);return c},eva=function(a,b,c,d){var e={};
g.Ra(e,dva(a,b));g.Ra(e,cva(a,b));d?g.Qb(e,a.D)?(d=a.C,e=a.D):d="_"+K3++:d=b.getAttribute("id")||"_"+K3++;a=N3(b,"t")+c;b=N3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.eh,e.eh=c;return new J3(a,b,0,d,e)},S3=function(a){L3.call(this);
this.D=a;this.o=new Map;this.B=new Map;this.C=new Map;this.u=new Map},T3=function(a){a=g.Rd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},fva=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.eh=b);if(2===f.o||3===f.o)b=f.u,f.u=f.eh,f.eh=b;return new J3(c,d,0,e,f)},V3=function(){this.A=this.time=this.mode=this.u=0;
this.B=new U3(this);this.C=new U3(this);this.o=[];this.clear()},hva=function(a,b,c){if(255===a&&255===b||!a&&!b)return{ri:a,
ah:b,result:0};a=gva[a];b=gva[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.ah===d;if(d)return{ri:a,ah:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ri:a,ah:b,result:2};return{ri:a,ah:b,result:3}},jva=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,iva(a.B,b,c,d))},kva=function(a,b){a.o.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.p(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?jva(a,d.Tw,d.Uw,b):1===d.type&&a.u&496&&iva(a.C,d.Tw,d.Uw,b);a.o.length=0},W3=function(){this.type=0},X3=function(){this.state=this.ah=this.ri=0},lva=function(){this.timestamp=this.o=0},Y3=function(a){this.C=a;
this.A=[];this.o=this.u=this.row=0;this.style=new W3;for(a=this.B=0;15>=a;a++){this.A[a]=[];for(var b=0;32>=b;b++)this.A[a][b]=new lva}},Z3=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.A[m][q];
if(0!==t.o){0===c&&(c=m,d=q);n=String.fromCharCode(t.o);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===t.o||32===q)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(q=a.A[h][m],t=q.o,0!==t&&(0===c&&(c=h,d=m),n=String.fromCharCode(t),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32===m||0===t)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},qva=function(a,b){switch(a){case 0:return mva[(b&127)-32];
case 1:return nva[b&15];case 2:return ova[b&31];case 3:return pva[b&31]}return 0},$3=function(a){return a.A[a.row][a.u]},a4=function(a,b,c){2<=b&&1<a.u&&(--a.u,$3(a).o=0);
var d=$3(a);d.timestamp=a.C.time+0;d.o=qva(b,c);32>a.u&&a.u++},rva=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.A[b+e][f],l=a.A[c+e][f];
h.o=l.o;h.timestamp=l.timestamp}},b4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},c4=function(a){a.row=0<a.o?a.o:1;
a.u=1;b4(a,0,15)},d4=function(a){this.A=a;
this.C=0;this.style=new W3;this.D=new Y3(this.A);this.G=new Y3(this.A);this.text=new Y3(this.A);this.u=this.D;this.B=this.G;this.o=this.u},e4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(Z3(d,c),c4(a.u),c4(a.B),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.B;e?d.u=1:d.o!==b&&(d.o>b?(Z3(d,c),b4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},sva=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.B},tva=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.A.mode=1<<a.o.B},U3=function(a){this.u=a;
this.C=0;this.A=new d4(this.u);this.D=new d4(this.u);this.o=new X3;this.B=this.A},iva=function(a,b,c,d){a.o.update();
b=hva(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ri;c=b.ah;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&a4(a,0,b),c&96&&a4(a,0,c),0!==b&&0!==c&&3===a.style.type&&Z3(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.ri=e,b.ah=c,b.state=2,b=e&8?a.D:a.A,a.B=b,a.u.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,h=1+d-c.o;rva(c,h,f,c.o);b=f;e=c.o;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));b4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:a4(b.o,0,32);break a;case 48:57===c?(d=b.o,$3(d).o=0,32>d.u&&d.u++):a4(b.o,1,c&15)}break;case 2:c&32&&a4(b.o,2,c&31);break;case 3:c&32&&a4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:sva(b);
break;case 33:d=b.o;1<d.u&&(--d.u,$3(d).o=0);break;case 36:d=b.o;b=$3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]===b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:e4(b,2,d);break;case 38:e4(b,3,d);break;case 39:e4(b,4,d);break;case 40:a4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.B;break;case 42:d=b.text;d.o=15;d.style.set(4);c4(d);tva(b);break;case 43:tva(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:Z3(a,d)}b4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;Z3(a,d);rva(a,b,b+1,a.o-1);b4(a,a.row,1)}break;case 46:b4(b.B,0,15);break;case 47:Z3(b.u,d),b.B.updateTime(b.A.time+0),d=b.B,b.B=b.u,b.u=d,sva(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},uva=function(){},f4=function(a,b,c){this.H=a;
this.G=c;this.version=this.D=this.B=this.o=0;this.u=new DataView(this.H);this.A=[]},g4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},h4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},i4=function(a,b){L3.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.o=new V3;this.o.u=1<<this.track},j4=function(a){if("string"===typeof a)return!1;
a=new f4(a,8,0);return vva(a)},vva=function(a){if(!(a.o<a.u.byteLength)||1380139777!==h4(a))return!1;
a.version=g4(a);if(1<a.version)return!1;g4(a);g4(a);g4(a);return!0},k4=function(){L3.call(this)},wva=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.bf=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var q=h.childNodes[n];if(3===q.nodeType)q=new I3(b,c,d,e.id,q.nodeValue,f||0<n,g.Ob(l)?void 0:l),m.push(q),e.o.push(q);else{var t={};g.Ra(t,l);wva(a,b,c,d,e,!0,q,t,m)}}},l4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},xva=function(a,b,c,d){d=Object.assign({mk:0},d);
return new J3(a,b,c,"_"+K3++,d)},m4=function(a){g.z.call(this);
this.u=a;this.o=null},zva=function(a){var b={};
if(a=x3(a))b.lang=a,yva.test(a)&&(b.o=1);return b},p4=function(a){g.OL.call(this,a);
this.K=a;this.A=this.K.O();this.videoData=this.K.getVideoData();this.ya=g.jL(this.K);this.B={Cb:{}};this.D={Cb:{}};this.N=[];this.J={};this.ca={};this.V=!1;this.sa=g.QL(this.videoData,this.K);this.za=!!this.videoData.captionTracks.length;this.Ba=!!this.videoData.Al;this.fa="3"===this.A.controlsType;this.u=this.G=this.H=this.aa=this.ma=null;this.ea=new m4(this.A);this.o=null;this.W=new g.zr(this);var b=null,c=g.po("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Zn(c));this.ga=b;b=a.app.C;
c=!(!b||!b.Zm());this.va=!(!b||!b.sj());this.C=this.fa&&c&&!this.sa;this.R=!this.C&&this.fa&&this.va&&this.sa;g.A(this,this.ea);this.C?this.ba=this.T=null:(this.T=new g.wn(this.YC,void 0,this),g.A(this,this.T),this.ba=new g.H(this.YN,2E3,this),g.A(this,this.ba));g.A(this,this.W);this.C||this.W.M(a,"resize",this.Bv);this.W.M(a,"onPlaybackAudioChange",this.rK);this.W.M(a,g.jC("captions"),this.Wc,this);this.W.M(a,"crx_captions",this.Ge,this);n4(this,o4(this,"display-settings")||{})},q4=function(a){if(1===
a.A.dh||1===a.videoData.dh||"alwayson"===g.BB(a.videoData,"yt:cc"))return!0;
if(2===a.A.dh){var b=o4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().Dr;return"ON"===c||"on"===g.BB(a.videoData,"yt:cc")},r4=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.co||"FORCED_ON"===c.Dr},t4=function(a,b){if(a.u){if(a.G&&a.G.o)return a.G.o;
var c=b;c||(c=a.Ba?!1:a.za?!1:!0);c=a.u.Gi(c);for(var d=[a.videoData.captionsLanguagePreference,a.A.captionsLanguagePreference,g.BB(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(x3(c[f])===d[e])return c[f];return a.G&&a.G.Pr?a.G.Pr:(d=c.find(function(h){return h.isDefault}))?d:c[0]||s4(a)}return null},s4=function(a){return a.G&&a.G.co},u4=function(a){var b=s4(a);
return!!b&&a.o===b},Ava=function(a,b){for(var c=a.K.app.C.wa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},w4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.V=c,a.V&&v4(a,"module-enabled",!!b));a.o=b;r4(a)&&(a.o=s4(a));a.load()},Bva=function(a,b){var c=a.ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&yva.test(d)&&(b.params.o=1);d=a.ya.getPlayerSize();switch(null!=b.params.mk?b.params.mk:1<b.o.length?1:0){case 1:return new G3(b,a.B,a.D,c,d.width,d.height,a.A.experiments);case 2:return new H3(b,a.B,a.D,c,d.width,d.height,a.A.experiments);default:return new F3(b,a.B,a.D,c,d.width,d.height,a.A.experiments)}},n4=function(a,b,c){c=void 0===c?!1:c;
var d=x4.Cb;a.B={};g.Ra(a.B,x4);a.B.Cb={};g.Ra(a.B.Cb,d);a.D={Cb:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;Q3.test(f);e.Cb.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;Q3.test(f);e.Cb.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||x4.windowColor;Q3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Cb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Cb.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.bf?3:d.bold?1:d.bf?2:0);f=f.Cb;switch(e){case 1:f.bold=!0;delete f.bf;break;case 2:delete f.bold;f.bf=!0;break;case 3:f.bold=!0;f.bf=!0;break;default:delete f.bold,delete f.bf}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Cb.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=x4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Cb.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Cb.fontFamily=f;a.loaded&&a.Bv();c&&v4(a,"display-settings",b)},Dva=function(a,b){if(b&&!a.H){var c=$ua({o:0,
lang:"en-GB"});a.H=[c,new I3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.yL(a.player,a.H)}else!b&&a.H&&(Cva(a,a.H),a.H=null)},Cva=function(a,b){g.HT(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.gb(this.N,c)},a);
a.T.Wa()},o4=function(a,b){if(!a.ga)return null;
try{var c=a.ga.get(b)}catch(d){a.ga.remove(b)}return c},v4=function(a,b,c){if(a.ga)try{a.ga.set(b,c)}catch(d){}};
g.eM.prototype.Bl=g.da(11,function(){for(var a=g.fe(document,"track",void 0,this.o),b=0;b<a.length;b++)g.ye(a[b])});
g.iM.prototype.Bl=g.da(10,function(){this.o.Bl()});
g.eM.prototype.Zm=g.da(9,function(){return!!this.o.textTracks});
g.iM.prototype.Zm=g.da(8,function(){return this.o.Zm()});
g.eM.prototype.vl=g.da(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.iM.prototype.vl=g.da(6,function(a){this.o.vl(a)});
g.tC.prototype.sj=g.da(5,function(){});
g.eM.prototype.sj=g.da(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.iM.prototype.sj=g.da(3,function(){return this.o.sj()});
g.Qu.prototype.so=g.da(1,function(a){return(a=this.vg(a))?a.o:0});
g.Bx.prototype.so=g.da(0,function(){return 0});
var yva=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;Iua.prototype.Gi=function(a){return a?this.o.concat(this.u):this.o};
g.r(z3,g.z);g.k=z3.prototype;g.k.Gi=function(a){return this.u.Gi(a)};
g.k.To=function(){};
g.k.Uo=function(){};
g.k.Tg=function(){};
g.k.Vj=function(){return""};
g.k.NB=function(){return!1};
g.k.Z=function(){this.Tg();g.z.prototype.Z.call(this)};
g.r(A3,z3);A3.prototype.To=function(a,b,c){var d=this;this.ha();b=this.Vj(a,b);this.Tg();this.o=g.xq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
A3.prototype.Uo=function(a){if(this.audioTrack)for(var b=g.p(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())y3(this.u,c.value);a()};
A3.prototype.Vj=function(a,b){var c=a.qc(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.ll()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=x3(a));return g.hq(c,d)};
A3.prototype.Tg=function(){this.o&&this.o.abort()};
B3.prototype.contains=function(a){a=g.rb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
B3.prototype.length=function(){return this.segments.length/2};
g.r(C3,g.z);g.k=C3.prototype;g.k.Z=function(){g.z.prototype.Z.call(this);this.u&&this.u.cancel()};
g.k.tB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Bb();var b=this.o;this.o=g.Wa(this.R.zg(a).o);b!==this.o&&this.H&&this.H()};
g.k.reset=function(){this.B=new B3;this.u&&(this.u.cancel(),this.u=null)};
g.k.Zy=function(){this.ha();var a;if(a=null!=this.o)a=this.o,a=a.o.Mg(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.ph(),a.o[0].duration?(this.B.contains(a.o[0].u)||Lua(this,a),this.o=g.Wa(a.o)):!g.O(this.J.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.D&&this.o.D+this.player.Bb()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.G.start()};
g.r(D3,z3);g.k=D3.prototype;g.k.To=function(a,b,c){var d=this;this.Tg();b=Nua(this,a.getId());b||(b=a.languageCode,b=this.ka.u?Oua(this,b,"386"):Oua(this,b));if(b){var e=1E3*(b.index.so(b.index.Xe())-b.index.pd(b.index.Xe()));this.o=new C3(new g.Bw,this.K,b,function(f,h){c(f,a,h,e)},this.C||g.Xs(b.info),function(){d.o&&d.o.reset();
d.A=!0})}};
g.k.NB=function(){var a=this.A;this.A=!1;return a};
g.k.Uo=function(a){var b;this.C?b=[new g.Is({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Is({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ka.u?Mua(this,"386"):Mua(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())y3(this.u,c.value);a()};
g.k.Tg=function(){this.o&&(this.o.dispose(),this.o=null)};
g.k.Vj=function(){return""};
g.r(E3,z3);E3.prototype.To=function(a,b,c){var d=this;this.ha();b=this.Vj(a,b);this.Tg();this.o=g.xq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
E3.prototype.Uo=function(a){var b=this,c=this.A,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.Cy&&(d.asrs=1);c=g.hq(c,d);this.Tg();this.o=g.xq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),q=l.getAttribute("name"),t=l.getAttribute("kind"),u=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),B="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");y3(b.u,new g.Is({languageCode:m,languageName:n,name:q,kind:t,id:u,is_servable:!0,is_translateable:B,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.C[m.languageCode]=m.languageName,b.B.push(m)}a()},
withCredentials:!0})};
E3.prototype.Vj=function(a,b){var c=this.A,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=x3(a));return c=g.hq(c,d)};
E3.prototype.Tg=function(){this.o&&this.o.abort()};
var Q3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Qua=["left","right","center","justify"];g.r(F3,g.Q);g.k=F3.prototype;g.k.VK=function(a,b){var c=g.Nh(this.element,this.element.parentElement);this.ma=a-c.x;this.sa=b-c.y;g.I(this.element,"ytp-dragging")};
g.k.UK=function(a,b){var c=g.Qh(this.element),d=a-this.ma-.02*this.playerWidth,e=b-this.sa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Rd(f,0,2));var h=(e+c.height/2)/this.va*3;h=Math.floor(g.Rd(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Rd(d,0,1);c=(e+h/2*c.height)/this.va;c=100*g.Rd(c,0,1);this.A.params.Ne=l;this.A.params.vf=c;this.A.params.ke=d;this.u.Ne=l;this.u.vf=c;this.u.ke=d;this.nC()};
g.k.SK=function(){g.In(this.element,"ytp-dragging")};
g.k.nC=function(){this.qj(this.D)};
g.k.qj=function(a){var b=Math.min(this.Sx(),this.maxWidth),c=this.Rx(),d="";3===this.A.params.o&&(d="rotate(180deg)");g.xh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.xr(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.ke+2;d=this.u.Ne;switch(d){case 0:case 3:case 6:b=this.u.Cb.fontSizeIncrement;!g.O(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.o&&3!==this.u.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.vf+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.xh(this.element,a)};
g.k.xr=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.V||this.D.length>b)b=0,this.V=!1,this.D=[],this.G=this.ba=this.W=null,g.we(this.C);for(;b<a.length;b++)Uua(this,a[b])};
g.k.Sx=function(){return 0};
g.k.Rx=function(){return 0};
g.k.toString=function(){return g.Q.prototype.toString.call(this)};g.r(G3,F3);G3.prototype.xr=function(a){var b=this.A.o;F3.prototype.xr.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Ra(d,c.o);g.Ra(d,Eva);var e=c.o;var f=d}Uua(this,c,d)}};
var Eva={fG:!0};g.r(H3,F3);g.k=H3.prototype;g.k.nC=function(){g.zn(this.ea)};
g.k.EM=function(){g.In(this.element,"ytp-rollup-mode");this.qj(this.Ba,!0)};
g.k.Rx=function(){return this.B?this.N:this.J};
g.k.Sx=function(){return this.B?this.J:this.N};
g.k.qj=function(a,b){this.Ba=a;if(this.A.params.u){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.ya=this.N;this.J=this.N=0;F3.prototype.qj.call(this,a);Zua(this,b);F3.prototype.qj.call(this,a)}else F3.prototype.qj.call(this,a)};g.r(I3,g.gC);I3.prototype.toString=function(){return g.gC.prototype.toString.call(this)};g.r(J3,g.gC);J3.prototype.toString=function(){return g.gC.prototype.toString.call(this)};
var K3=0;g.r(L3,g.z);L3.prototype.A=function(){return[]};
L3.prototype.reset=function(){};g.r(M3,L3);M3.prototype.reset=function(){this.H={};this.u=this.o=null;this.G=!0};
M3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Ra(l,this.B[m]);m=O3(c,"b");null!=m&&
(l.bold=m);m=O3(c,"i");null!=m&&(l.bf=m);m=O3(c,"u");null!=m&&(l.underline=m);m=P3(c,"et");null!=m&&(l.charEdgeStyle=m);m=P3(c,"of");null!=m&&(l.offset=m);m=R3(c,"bc");null!=m&&(l.background=m);m=R3(c,"ec");null!=m&&(l.Gr=m);m=R3(c,"fc");null!=m&&(l.color=m);m=P3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=N3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=N3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=N3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=P3(c,"rb");null!=m&&10!==m&&0!==m&&(l.Yb=
10<m?m-1:m);c=P3(c,"hg");null!=c&&(l.zy=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.R[d]=cva(this,c);break;case "wp":d=c.getAttribute("id"),this.J[d]=dva(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=eva(this,d,e,!1);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.C;m=!!O3(d,
"a");n=(N3(d,"t")||0)+n;var q=N3(d,"d")||5E3;m||(!this.G&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var t=m?6:5,u=d.getAttribute("p");u=u?this.B[u]:null;var w=Array.from(d.childNodes);w.length&&(this.G=null!=d.getAttribute("d"));for(var B=0;B<w.length;B++){var D=w[B],E=void 0;0<B&&(m=!0);var F=void 0;1===D.nodeType&&(F=D);if(F&&"s"===F.tagName){if((D=(D=F.getAttribute("p"))?this.B[D]:null)&&D.Yb&&(1===D.Yb?(D=w.slice(B,B+4),4===D.length&&
(E=bva(n,q,l,m,t,D,this.B),B+=3)):E=bva(n,q,l,m,t,[F],this.B)),!E){var G=F;E=n;F=q;D=l;var aa=m,ma=t,dc=G.textContent?G.textContent:"",tb=G.getAttribute("p");tb=tb?this.B[tb]:null;G=N3(G,"t")||0;E=new I3(E+G,F-G,ma,D,dc,aa,tb)}}else E=new I3(n,q,t,l,D.textContent||"",m,u);h.push(E);this.u=E}if(0<h.length)for(h[0].windowId===this.C&&(this.o=eva(this,d,e,!0),c.push(this.o)),d=g.p(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.o.id,this.o.o.push(h),c.push(h)}e=c}else e=[];return e};var Fva=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(S3,L3);S3.prototype.reset=function(){this.u.clear()};
S3.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.o.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.bf=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.Gr=T3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=T3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=T3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Yb=10<l?l-1:l,h.tf=Fva.get(h.Yb));f.hgHorizGroup&&(h.zy=f.hgHorizGroup);this.o.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.D),void 0!==f.mhModeHint&&(h.mk=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.A=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=T3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.ke=f.ahHorPos),void 0!==f.apPoint&&(h.Ne=f.apPoint),void 0!==f.avVerPos&&(h.vf=f.avVerPos),void 0!==f.ccCols&&(h.eh=f.ccCols),void 0!==f.rcRows&&(h.u=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=fva(this,m,e,f,h),d.push(e),this.u.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+K3++,l=fva(this,m,e,f,h),d.push(l),this.u.set(h,l));0===f&&(f=5E3);l=this.u.get(h);var n=
!!m.aAppend,q=n?6:5,t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var w=t[m],B=w.utf8;if(B){var D=w.tOffsetMs||0,E=null;w.pPenId&&(E=this.o.get(w.pPenId));if(2===(null!=l.params.mk?l.params.mk:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(w=E&&1===E.Yb)if(w=m,w+3>=t.length||!t[w+1].pPenId||!t[w+2].pPenId||!t[w+3].pPenId)w=!1;else{var F=t[w+1].pPenId;(F=this.o.get(F))&&F.Yb&&2===F.Yb?(F=t[w+2].pPenId,F=this.o.get(F),!F||!F.Yb||3>F.Yb?w=!1:(F=t[w+3].pPenId,w=(F=this.o.get(F))&&
F.Yb&&2===F.Yb?!0:!1)):w=!1}if(w){D=t[m+1].utf8;w=t[m+3].utf8;F=t[m+2].utf8;var G=this.o.get(t[m+2].pPenId);B=ava(B,D,F,w,G);n=new I3(e,f,q,h,B,n,E);m+=3}else n=new I3(e+D,f-D,q,l.id,B,n,E||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};V3.prototype.clear=function(){this.A=this.time=this.mode=0;this.o=[];this.reset()};
V3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var gva=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];W3.prototype.set=function(a){this.type=a};
W3.prototype.get=function(){return this.type};
X3.prototype.clear=function(){this.state=0};
X3.prototype.update=function(){this.state=2===this.state?1:0};
X3.prototype.isValid=function(){return 0!==this.state};
X3.prototype.matches=function(a,b){return this.isValid()&&a===this.ri&&b===this.ah};
lva.prototype.reset=function(){this.timestamp=this.o=0};
Y3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
Y3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
Y3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.o=0;this.u=this.row=1};
var mva=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],nva=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],ova=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],pva=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];d4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.u=this.D;this.B=this.G;this.o=this.u;var c=(a<<2)+(b<<1);this.D.reset(c);this.G.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
U3.prototype.reset=function(a){this.C=a;this.o.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};uva.prototype.C=function(){};g.r(f4,uva);f4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+K3++;c=c/1E3-this.G;d=d/1E3-this.G;a=new J3(c,d-c,5,f,{textAlign:0,Ne:0,ke:2.5*b,vf:5.33*a});e=new I3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.r(i4,L3);i4.prototype.A=function(a){a=new f4(a,a.byteLength,this.u);if(vva(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.B=h4(a)*(1E3/45):1===a.version&&(a.B=4294967296*h4(a)+h4(a)),a.D=g4(a);0<a.D;a.D--){var b=g4(a),c=g4(a),d=g4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,Tw:c,Uw:d,order:b.o.length}))}kva(this.o,a);return a.A}return[]};
i4.prototype.reset=function(){this.o.clear()};g.r(k4,L3);
k4.prototype.A=function(a,b){for(var c=[],d=a.split(Gva),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!Hva.test(f)){var l=y4.exec(f);if(l&&4<=l.length){var m=l4(l[1]),n=l4(l[2])-m;m+=h;var q=(l=l[3])?l.split(" "):[];l={};var t=null,u="",w=null,B="";l.textAlign=2;q=g.p(q);for(var D=q.next();!D.done;D=q.next())if(D=D.value.split(":"),2===D.length){var E=D[1];switch(D[0]){case "line":D=E.split(",");D[0].endsWith("%")&&(t=D[0],l.vf=Number.parseInt(t,10),2===D.length&&(u=D[1].trim()));break;case "position":D=
E.split(",");w=D[0];l.ke=Number.parseInt(w,10);2===D.length&&(B=D[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}t||(l.vf=100,u||(u="end"));if(!w)switch(l.textAlign){case 0:l.ke=0;break;case 1:l.ke=100;break;default:l.ke=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(B){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Ne=0>t||8<t?7:t;f=f.substring(y4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");B=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=xva(m,n,5,B),n=new I3(m,n,5,h.id,l,!1,g.Ob(f)?void 0:f),c.push(h),c.push(n),h.o.push(n);else for(u=l.split(Iva),1===u.length?(l=5,B=xva(m,n,l,B)):(t=l=6,B=Object.assign({eh:32},B),B=new J3(m,n,t,"_"+K3++,B)),c.push(B),t=m,w=0;w<u.length;w++)q=u[w],0===w%2?(D=g.v1("<html>"+q+"</html>"),D.getElementsByTagName("parsererror").length?
(E=D.createElement("span"),E.appendChild(D.createTextNode(q))):E=D.firstChild,wva(this,t,n-(t-m),l,B,0<w,E,f,c)):t=l4(q)+h}y4.lastIndex=0}}return c};
var Hva=/^NOTE/,Gva=/(?:\r\n|\r|\n){2,}/,y4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Iva=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(m4,g.z);m4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
m4.prototype.reset=function(){this.o&&this.o.reset()};
m4.prototype.Z=function(){g.z.prototype.Z.call(this);this.clear()};var x4={windowColor:"#080808",windowOpacity:0,textAlign:2,Ne:7,ke:50,vf:100,Cb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(p4,g.OL);g.k=p4.prototype;g.k.Z=function(){if(this.C||this.R){var a=this.K.app.C;a&&!a.ha()&&a.Bl()}else Dva(this,!1);g.OL.prototype.Z.call(this)};
g.k.load=function(){var a=this;g.OL.prototype.load.call(this);var b=!g.O(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.G=this.player.getAudioTrack();if(this.u)this.o&&(this.ea.clear(),this.C?Ava(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.To(this.o,"json3",function(d,e,f,h){if(d){a.u.NB()&&(a.N=[],g.BR(a.K.app,"captions",void 0),a.T.Wa(),a.ea.reset());var l=a.ea;f=f||0;h=h||0;if(l.u.ia("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.fv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),j4(d)||(d=g.cg(new Uint8Array(d))))}}else"string"===typeof d||j4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.fv(m,0,1835295092))&&m.size?g.cg(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,q=f,t=h;if(!j4(n))throw Error("Invalid binary caption track data");l.o||(l.o=new i4(t,e));var u=l.o.A(n,q)}else{if("WEBVTT"===
d.substring(0,6))e=d,t=f,l.o||(l.o=new k4),q=l.o.A(e,t),.01>Math.random()&&g.Mq(Error("Deprecated subtitles format in web player: WebVTT")),n=q;else b:{q=d;if("{"===q[0])try{l.o||(l.o=new S3(zva(e)));n=l.o.A(q,f);break b}catch(G){g.Lq(G);n=[];break b}t=g.v1(q);if(!t||!t.firstChild){var w=Error("Invalid caption track data");w.params=q;throw w;}if("timedtext"===t.firstChild.tagName){if(3===Number(t.firstChild.getAttribute("format"))){l.o||(l.o=new M3(zva(e),l.u));n=l.o.A(t,f);break b}var B=Error("Unsupported subtitles format in web player (Format2)");
B.params=q;throw B;}if("transcript"===t.firstChild.tagName){var D=Error("Unsupported subtitles format in web player (Format1)");D.params=q;throw D;}var E=Error("Invalid caption track data");E.params=q;throw E;}u=n}var F=u}catch(G){g.Lq(G),l.clear(),F=[]}else F=[];g.yL(a.player,F);!a.V||a.R||u4(a)||g.Wy(a.A)||g.Xy(a.A)||(a.ba.We(),F=$ua({Ne:0,ke:5,vf:5,u:2,textAlign:0,o:0,lang:"en-GB"}),a.aa=[F],l=["Click "," for settings"],a.ma||(u=new g.Fu(g.nN()),g.A(a,u),a.ma=u.element),u=F.end-F.start,(e=g.Js(a.o))&&
a.aa.push(new I3(F.start,u,0,F.id,e)),a.aa.push(new I3(F.start,u,0,F.id,l[0]),new I3(F.start,u,0,F.id,a.ma,!0),new I3(F.start,u,0,F.id,l[1],!0)),g.yL(a.player,a.aa),a.ba.Wa());!a.V||a.R||u4(a)||(v4(a,"module-enabled",!0),a.G&&(a.G.o=a.o),(F=g.V(a.player.app))&&g.CI(F.C));a.V=!1}}),!b||this.C||this.R||u4(this)||this.player.ra("captionschanged",w3(this.o))),b||(this.o&&!u4(this)?this.player.ra("captionschanged",w3(this.o)):this.player.ra("onCaptionsTrackListChanged"));
else{var c;this.sa?c=new D3(this.videoData.ka,this.player):this.za?c=new A3(this.A,this.videoData,this.player.getAudioTrack()):c=new E3(this.videoData.Al,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.A.captionsLanguagePreference||g.BB(this.videoData,"yt:cc_default_lang")||this.A.Nc,this.videoData.Cr,this.A);this.u=c;g.A(this,this.u);c.Uo(function(){var d;a.V||q4(a)?d=t4(a,a.V):r4(a)&&(d=s4(a));if(a.C||a.R){for(var e=a.u.Gi(!0),f=[],h=0;h<e.length;h++){var l=e[h],m=g.se("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.Js(l));m.setAttribute("srclang",x3(l));m.setAttribute("id",l.toString());a.R||m.setAttribute("src",a.u.Vj(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.K.app.C;d.vl(f);f=d.wa();a.va&&a.W.M(f.textTracks,"change",a.hN)}else!a.o&&d&&w4(a,d),a.player.ra("onCaptionsTrackListChanged"),a.player.ra("onApiChange")})}};
g.k.unload=function(){this.C&&this.o?Ava(this,!1):(this.ba&&this.ba.We(),g.BR(this.player.app,"captions",void 0),this.N=[],this.u&&this.u.Tg(),this.ea.clear(),this.H&&g.yL(this.player,this.H),this.Bv());g.OL.prototype.unload.call(this);var a=g.V(this.player.app);a&&g.CI(a.C);this.player.ra("captionschanged",{})};
g.k.create=function(){(this.fa?this.C||this.R:r4(this)||q4(this))&&this.load()};
g.k.getTrackById=function(a){for(var b=this.u.Gi(!0),c=0;c<b.length;c++)if(b[c].toString()===a)return b[c];return null};
g.k.hN=function(){for(var a=this.K.app.C.wa().textTracks,b=null,c=0;c<a.length;c++)"showing"===a[c].mode&&(b=this.getTrackById(a[c].id));(this.loaded?this.o:null)!==b&&w4(this,b,!0)};
g.k.LO=function(){!this.o&&this.C||this.unload()};
g.k.Wc=function(a){this.N.push(a);this.T.Wa()};
g.k.Ge=function(a){g.gb(this.N,a);this.u instanceof D3&&this.u.C&&g.HT(this.player.app,[a],void 0);this.T.Wa()};
g.k.SN=function(a){if(a instanceof J3){var b=this.J[a.id];b&&b.A!==a&&(b.dispose(),delete this.J[a.id],b=null);b||(b=Bva(this,a))&&(this.J[a.id]=b)}else b=a.windowId,this.ca[b]||(this.ca[b]=[]),this.ca[b].push(a)};
g.k.YN=function(){Cva(this,this.aa);this.aa=null};
g.k.YC=function(){var a=this;this.T.stop();g.Pb(this.ca);this.N.sort(g.iC);var b=this.N;if(this.H){var c=(0,g.ze)(b,function(d){return-1===this.H.indexOf(d)},this);
c.length&&(b=c)}(0,g.y)(b,this.SN,this);g.Bb(this.J,function(d,e){a.ca[e]?(d.element.parentNode||(d instanceof H3||d instanceof G3||g.Eb(a.J,function(f,h){h!==e&&f.A.params.Ne===d.A.params.Ne&&f.A.params.ke===d.A.params.ke&&f.A.params.vf===d.A.params.vf&&(f.dispose(),delete a.J[h]);return h===e},a),g.CL(a.player,d.element,4)),d.qj(a.ca[e])):(d.dispose(),delete a.J[e])},this)};
g.k.fO=function(){n4(this,{},!0);g.O(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ra("captionssettingschanged")};
g.k.vF=function(){var a=x4.Cb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.bf?3:a.bold?1:a.bf?2:0,textOpacity:a.textOpacity,windowColor:x4.windowColor,windowOpacity:x4.windowOpacity};var b=o4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.gD=function(a,b){var c={};g.Ra(c,o4(this,"display-settings"));g.Ra(c,a);n4(this,c,b);this.player.ra("captionssettingschanged")};
g.k.Bv=function(){!this.C&&this.loaded&&(g.Bb(this.J,function(a,b){a.dispose();delete this.J[b]},this),this.YC())};
g.k.Sc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Rd(b,-2,4);this.gD({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&w4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.A.A&&v4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Na(b))break;if(g.Ob(b)){w4(this,null,!0);break}for(var d=this.u.Gi(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
Hua(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||w4(this,c,!0)}else return this.loaded&&this.o&&!u4(this)?w3(this.o):{};return"";case "tracklist":return this.u?(0,g.Hc)(this.u.Gi(!(!b||!b.includeAsr)),function(h){return w3(h)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.C||void 0===b||Dva(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.A&&a.push("stickyLoading");return a};
g.k.OG=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.k.HO=function(){this.loaded&&this.o&&!u4(this)?(v4(this,"module-enabled",!1),this.unload(),r4(this,!0)&&w4(this,s4(this),!1)):w4(this,u4(this)||!this.o?t4(this,!0):this.o,!0)};
g.k.rK=function(){var a=u4(this);r4(this,a)?w4(this,this.player.getAudioTrack().co,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.fa?this.C||this.R:r4(this)||q4(this))&&(a?w4(this,t4(this),!1):this.load()))};g.cM.captions=p4;})(_yt_player);
